version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Generate Fibonacci series
          command: python generate_fibonacci.py

workflows:
  version: 2
  build:
    jobs:
      - build
